// ── engine-core ──────────────────────────────────────────────────────────────
// Headless, deterministic, framework-agnostic runtime spine for the grid CRPG
// base (per the Implementation-Grounded Base Systems v3 spec). It owns seeded
// randomness, a structured event stream, versioned registries, and the
// command → validate → effect → event pipeline. It contains no React, DOM, or
// zustand imports, so it can be driven headlessly in tests and adopted
// incrementally by the existing runtime behind compatibility adapters.

export { RNG, RngStreams, hashSeed } from "./rng";
export {
  ENERGY_PER_FINE_STEP,
  ENERGY_PER_MACRO_STEP,
  FINE_CARDINAL_DIRECTIONS,
  FINE_HALF_EXTENT,
  FINE_PER_MACRO,
  actorFootprintCells,
  areAdjacentMacro,
  coordKey,
  fineBlockForMacro,
  fineCenterOfMacro,
  fineChebyshevDistance,
  fineCoord,
  fineCoordKey,
  fineManhattanDistance,
  fineOfMacro,
  footprintContainsCell,
  footprintIntersectsLeadingEdge,
  footprintLeadingCells,
  footprintsOverlap,
  macroCoord,
  macroCoordKey,
  macroKeyOfFine,
  macroManhattanDistance,
  macroOfFine,
  parseFineCoordKey,
  sameMacroCoord,
  scaleMacroDistanceToFine,
  withinSameMacroTile,
} from "./gridCoordinates";
export type { FineCoord, GridCoord, GridCoordKey, MacroCoord } from "./gridCoordinates";
export {
  expandGamePackageToFine,
  expandMapToFine,
  getFineGamePackage,
  isFineExpandedPackage,
} from "./fineWorld";
export {
  LARGE_MAP_CELL_THRESHOLD,
  RUNTIME_SECTOR_CACHE_LIMIT,
  RUNTIME_SECTOR_HALO,
  RUNTIME_SECTOR_SIZE,
  RuntimeMapGrid,
  getRuntimeMapGrid,
  isLargeAuthoredMap,
  materializeLargeMapWindow,
} from "./runtimeMapGrid";
export type { RuntimeGridBounds, RuntimeMapGridStats } from "./runtimeMapGrid";
export { EventBus } from "./events";
export type { EngineEvent, EventListener } from "./events";
export { Registry } from "./registry";
export {
  activeReactiveTaskForActor,
  decideEntityAction,
  reactiveSignalFromTask,
  recordEntityBehaviorDecision,
} from "./behaviorArbiter";
export type {
  BehaviorActionKind,
  BehaviorCommitmentRecord,
  BehaviorContext,
  BehaviorReactiveSignal,
  BehaviorTier,
  EntityBehaviorIntentRecord,
  EntityBehaviorState,
  EntityBehaviorWorldState,
} from "./behaviorArbiter";
export {
  Engine,
  ChangeMapHandler,
  FireTriggerHandler,
  OpenContainerHandler,
  MoveEntityHandler,
  WaitHandler,
  StowInContainerHandler,
  TakeAllFromContainerHandler,
  TakeFromContainerHandler,
  UnlockContainerHandler,
  TakeItemHandler,
  DropItemHandler,
  OpenDoorHandler,
  CloseDoorHandler,
  PushObjectHandler,
  PullObjectHandler,
  DragObjectHandler,
  CarryObjectHandler,
  BreakObjectHandler,
  CleanSurfaceHandler,
  DecaySurfacesHandler,
  IgniteFireHandler,
  ExtinguishFireHandler,
  AdvanceEnvironmentHandler,
  EmitSoundHandler,
  SearchContainerHandler,
  SetSwitchHandler,
  SetQuestHandler,
  GiveItemHandler,
  RemoveItemHandler,
  GiveCurrencyHandler,
  CastSkillHandler,
  CompleteQuestObjectiveHandler,
  RemoveCurrencyHandler,
  MeleeAttackHandler,
  UpdateCombatSessionHandler,
  AdvanceCombatTurnHandler,
  EnemyTurnHandler,
  AdjustFactionRepHandler,
  ReadDocumentHandler,
  LearnSkillHandler,
  SetPlayerPositionHandler,
  TeleportPlayerHandler,
  SetEntityPositionHandler,
  SetPlayerSpriteHandler,
  HealPlayerHandler,
  RestorePartyHandler,
  AddPartyMemberHandler,
  RemovePartyMemberHandler,
  AdvanceClockHandler,
  ModifyPlayerStatsHandler,
  SetEntityHiddenHandler,
  RecordBarkHandler,
  GameEndHandler,
  ChooseDialogueOptionHandler,
  BuyShopItemHandler,
  SellInventoryItemHandler,
  moveEntityEffect,
  registerCoreCommands,
} from "./pipeline";
export type {
  Command,
  CommandHandler,
  Effect,
  GridEntity,
  GridWorld,
  InteractiveGridWorld,
  GroundItemRef,
  DroppedItemRef,
  PushableObjectRef,
  BreakableObjectRef,
  SurfaceLayerRef,
  EnvironmentCellRef,
  ContainerItemRef,
  ContainerRef,
  CombatAttackOutcome,
  CombatPartyFollowerRef,
  CombatSessionUpdateOptions,
  CombatSessionUpdateOutcome,
  CombatTurnAdvanceOutcome,
  DoorRef,
  DialogueChoiceEffectOutcome,
  DialogueChoiceOutcome,
  EnemyTurnOutcome,
  MapTransitionRef,
  QuestObjectiveCompletion,
  ShopTransactionOutcome,
  SkillCastHit,
  SkillCastOutcome,
  TriggerRef,
  DispatchResult,
  ValidationResult,
} from "./pipeline";
export { InMemoryGridWorld } from "./world";
export {
  KERNEL_DEFAULT_PLANE_ID,
  appendKernelFactsToSave,
  actorInventoryHolderId,
  containerInventoryHolderId,
  createKernelFactsFromEngineEvents,
  createKernelSnapshotFromV1,
  destroyedHolderId,
  equipmentSlotHolderId,
  handSlotHolderId,
  hiddenCacheHolderId,
  kernelInstanceId,
  shopStockHolderId,
  worldCellHolderId,
} from "./kernel";
export type {
  KernelExposureRecord,
  KernelFactAdapter,
  KernelFactAdapterContext,
  KernelFactBuildOptions,
  KernelHolder,
  KernelHolderKind,
  KernelInstanceKind,
  KernelLocation,
  KernelObjectInstance,
  KernelSnapshot,
  KernelTransactionKind,
  KernelTransactionRecord,
  KernelTransferRecord,
  KernelWorldFact,
} from "./kernel";
export {
  CONTAINER_OBJECT_BLUEPRINT_ID,
  DOOR_OBJECT_BLUEPRINT_ID,
  ITEM_OBJECT_BLUEPRINT_ID,
  PHYSICAL_OBJECT_BLUEPRINT_ID,
  ROOT_OBJECT_BLUEPRINT_ID,
  applyGameObjectCascadeDispatchToSave,
  applyGameObjectPartEmissionsToSave,
  createGameObjectModelSnapshotFromKernel,
  createGameObjectModelSnapshotFromV1,
  createGameObjectRuntimeFromKernelInstance,
  dispatchGameObjectEventCascade,
  dispatchGameObjectEvent,
  resolveGameObjectBlueprint,
  resolveGameObjectBlueprints,
} from "./objectModel";
export type {
  GameObjectCascadeDispatchEntry,
  GameObjectCascadeDispatchResult,
  GameObjectEvent,
  GameObjectEventDispatchResult,
  GameObjectModelSnapshot,
  GameObjectPartEmission,
  GameObjectPartConsequenceResult,
  GameObjectRuntime,
  ResolvedGameObjectBlueprint,
  ResolvedGameObjectPart,
} from "./objectModel";
export {
  PLAYER_ENTITY_ID,
  V1GridWorld,
  createV1GridWorld,
  dispatchV1MoveEntity,
  dispatchV1Wait,
  dispatchV1ChangeMap,
  dispatchV1FireTrigger,
  dispatchV1OpenContainer,
  dispatchV1StowInContainer,
  dispatchV1TakeAllFromContainer,
  dispatchV1TakeFromContainer,
  dispatchV1UnlockContainer,
  dispatchV1SearchContainer,
  dispatchV1TakeItem,
  dispatchV1DropItem,
  dispatchV1OpenDoor,
  dispatchV1CloseDoor,
  dispatchV1PushObject,
  dispatchV1PullObject,
  dispatchV1DragObject,
  dispatchV1CarryObject,
  dispatchV1BreakObject,
  dispatchV1CleanSurface,
  dispatchV1DecaySurfaces,
  dispatchV1IgniteFire,
  dispatchV1ExtinguishFire,
  dispatchV1AdvanceEnvironment,
  dispatchV1EmitSound,
  dispatchV1AdvanceNpcTasks,
  dispatchV1StartProcess,
  dispatchV1InterruptProcess,
  dispatchV1AdvanceProcesses,
  dispatchV1AdvanceSimulationRegions,
  dispatchV1AdaptSimulationSemantics,
  dispatchV1SetSwitch,
  dispatchV1SetQuest,
  dispatchV1GiveItem,
  dispatchV1RemoveItem,
  dispatchV1GiveCurrency,
  dispatchV1RemoveCurrency,
  dispatchV1AdjustFactionRep,
  dispatchV1ReadDocument,
  dispatchV1LearnSkill,
  dispatchV1CompleteQuestObjective,
  dispatchV1SetPlayerPosition,
  dispatchV1TeleportPlayer,
  dispatchV1SetEntityPosition,
  dispatchV1SetPlayerSprite,
  dispatchV1HealPlayer,
  dispatchV1RestoreParty,
  dispatchV1AddPartyMember,
  dispatchV1RemovePartyMember,
  dispatchV1AdvanceClock,
  dispatchV1ModifyPlayerStats,
  dispatchV1SetEntityHidden,
  dispatchV1RecordBark,
  dispatchV1GameEnd,
  dispatchV1AttendNode,
  dispatchV1ChooseDialogueOption,
  dispatchV1BuyShopItem,
  dispatchV1SellInventoryItem,
  dispatchV1MeleeAttack,
  dispatchV1CastSkill,
  dispatchV1UpdateCombatSession,
  dispatchV1AdvanceCombatTurn,
  dispatchV1EnemyTurn,
  dispatchV1EnemyPulse,
  getV1NearbyHostiles,
  getV1ControlledCombatant,
  getV1CombatantSnapshot,
  getV1SkillTargetCells,
  getV1SkillRangeCells,
  getV1DoorKey,
} from "./v1Runtime";
export type {
  V1GridWorldOptions,
  V1MoveDispatchOptions,
  V1WaitDispatchOptions,
  V1EnemyPulseDispatchOptions,
  V1ChangeMapDispatchOptions,
  V1TriggerDispatchOptions,
  V1ContainerDispatchOptions,
  V1ContainerItemDispatchOptions,
  V1ContainerStowDispatchOptions,
  V1DropItemDispatchOptions,
  V1CellDispatchOptions,
  V1PushObjectDispatchOptions,
  V1DecaySurfacesDispatchOptions,
  V1AdvanceEnvironmentDispatchOptions,
  V1EmitSoundDispatchOptions,
  V1AdvanceNpcTasksDispatchOptions,
  V1StartProcessDispatchOptions,
  V1InterruptProcessDispatchOptions,
  V1AdvanceProcessesDispatchOptions,
  V1AdvanceSimulationRegionsDispatchOptions,
  V1AdaptSimulationSemanticsDispatchOptions,
  V1StateDispatchOptions,
  V1SetSwitchDispatchOptions,
  V1SetQuestDispatchOptions,
  V1ItemGrantDispatchOptions,
  V1CurrencyDispatchOptions,
  V1FactionRepDispatchOptions,
  V1DocumentDispatchOptions,
  V1SkillDispatchOptions,
  V1QuestObjectiveDispatchOptions,
  V1PositionDispatchOptions,
  V1TeleportDispatchOptions,
  V1EntityPositionDispatchOptions,
  V1PlayerSpriteDispatchOptions,
  V1HealPlayerDispatchOptions,
  V1PartyMemberDispatchOptions,
  V1ClockDispatchOptions,
  V1ModifyPlayerStatsDispatchOptions,
  V1SetEntityHiddenDispatchOptions,
  V1BarkDispatchOptions,
  V1GameEndDispatchOptions,
  V1AttendNodeDispatchOptions,
  V1AttendNodeDispatchResult,
  V1ChooseDialogueOptionDispatchOptions,
  V1ShopBuyDispatchOptions,
  V1ShopSellDispatchOptions,
  V1MeleeAttackDispatchOptions,
  V1CastSkillDispatchOptions,
  V1CombatSessionDispatchOptions,
  V1CombatTurnDispatchOptions,
  V1SkillTargetOptions,
  V1SkillTargetResult,
  V1NearbyHostilesOptions,
  V1CombatantSnapshot,
} from "./v1Runtime";
export {
  BUILTIN_STATUSES,
  getStatusDef,
  applyStatus,
  tickStatuses,
  statModifiers,
} from "./statuses";
export type { StatusDef, StatusInstance, StatusKind, StatusTickResult } from "./statuses";
export {
  ALDERAMONTICO_EMOTIONAL_VERBS,
  applyAlderamonticoEmotionalImpulse,
  applyAlderamonticoEmotionalVerbToSave,
  applyAlderamonticoGridAmplification,
  applyAlderamonticoGridToActor,
  advanceAlderamonticoEmotionalDecayForSave,
  advanceAlderamonticoGridRegionsForSave,
  attendAlderamonticoActor,
  advanceAlderamonticoActorFromPhysical,
  advanceAlderamonticoGlass,
  alderamonticoImpulseHasEffect,
  applyAlderamonticoImpulseToSave,
  alderamonticoAttendReadingId,
  buildAlderamonticoConditionReadout,
  closeAlderamonticoAttendNode,
  dispatchAlderamonticoAttendNode,
  getAlderamonticoEmotionalVerb,
  getVisibleAlderamonticoAttendReadings,
  isAlderamonticoEmotionalVerb,
  openAlderamonticoAttendNode,
  relaxAlderamonticoEmotionalAxes,
  selectAlderamonticoAttendReading,
  defaultAlderamonticoActorState,
  defaultAlderamonticoEmotionalAxes,
  defaultAlderamonticoSaveState,
  deriveAlderamonticoEmotionalRegions,
  deriveAlderamonticoNamedEmotions,
  dominantAlderamonticoGridAxis,
  emotionalImpulseFromPhysicalState,
  ensureAlderamonticoActorState,
  entityEmotionalSeed,
  inferAlderamonticoBehavior,
  projectAlderamonticoActorEmotionalStates,
  resolveAlderamonticoActorAxes,
  resolveAlderamonticoBehavior,
  syncAlderamonticoActorEmotionalStates,
  advanceAlderamonticoAttendNode,
  upsertAlderamonticoActorState,
  zoneProfileEmotionalSeed,
} from "./alderamonticoState";
export type {
  AlderamonticoActorStateRecord,
  AlderamonticoActiveAttendNodeRecord,
  AlderamonticoAttendFlagEffect,
  AlderamonticoAttendNode,
  AlderamonticoAttendNodeDispatchOptions,
  AlderamonticoAttendNodeResult,
  AlderamonticoAttendReading,
  AlderamonticoAttendReadingEffect,
  AlderamonticoAttendRecord,
  AlderamonticoAttendTimeout,
  AlderamonticoAttendTruth,
  AlderamonticoBehaviorMode,
  AlderamonticoConditionReadout,
  AlderamonticoEmotionalAxes,
  AlderamonticoEmotionalAxis,
  AlderamonticoEmotionalImpulse,
  AlderamonticoEmotionalRegions,
  AlderamonticoEmotionalVerbDefinition,
  AlderamonticoEmotionalVerbKind,
  AlderamonticoEmotionalVerbResult,
  AlderamonticoGridAmplificationResult,
  AlderamonticoGridAxis,
  AlderamonticoGridExposureResult,
  AlderamonticoGridExposureSummary,
  AlderamonticoNamedEmotion,
  AlderamonticoSaveState,
} from "./alderamonticoState";
export {
  CLOCK_PHASE_LABELS,
  buildConditionContext,
  computeShopPrice,
  evaluateCondition,
  findEligibleSwitchChangeTriggers,
  findCutsceneLabelIndex,
  getAvailableShopStock,
  getClockPhaseId,
  getVisibleDialogueOptions,
  isDialogueOptionVisible,
  isMapExitEligible,
  isTriggerEligible,
  resolveDialogueNode,
  resolveDialogueChoice,
  resolveEnding,
  selectEligibleBark,
  shouldRunCutsceneBranch,
} from "./story";
export type {
  BarkSelectionOptions,
  ClockPhaseId,
  ConditionContext,
  DialogueChoiceEffect,
  DialogueChoiceResolution,
  DialogueOptionData,
  EndingResolution,
  ShopStockEntry,
} from "./story";
export {
  createSimulationDebugOverlays,
  createSimulationSnapshotFromV1,
  getSimulationMap,
} from "./simulation";
export type {
  SimulationCellState,
  SimulationDebugOverlay,
  SimulationDebugOverlayCell,
  SimulationMapSnapshot,
  SimulationOccupantKind,
  SimulationSurfaceKind,
  SimulationSurfaceState,
} from "./simulation";
export {
  createImmersiveIlluminationSnapshotFromV1,
  createImmersiveViewerVisibilityFromV1,
  queryImmersiveIlluminationAtCell,
  queryImmersiveVisualAcquisition,
  resolveImmersiveLightSources,
} from "./visibility";
export type {
  ImmersiveIlluminationCell,
  ImmersiveIlluminationContribution,
  ImmersiveIlluminationSnapshot,
  ImmersiveLightMobility,
  ImmersiveLightSourceKind,
  ImmersiveResolvedLightSource,
  ImmersiveViewerVisibilityOptions,
  ImmersiveViewerVisibilitySnapshot,
  ImmersiveVisualAcquisitionCause,
  ImmersiveVisualAcquisitionQuery,
  ImmersiveVisualAcquisitionResult,
} from "./visibility";
export {
  CHEM_SPILL_LIQUIDS,
  applyChemistrySpillToSave,
  applyChemistryVerbToSave,
  advanceChemistryForSave,
  buildAuthoredChemistryGrid,
  chemActorPhysicalStateFromCell,
  decayActorPhysicalStateRecord,
  initializeAuthoredChemistryForSave,
  isChemistryVerb,
  readChemistryGridForSave,
} from "./chemistryRuntime";
export type { ChemActorExposure, ChemistryVerbResult } from "./chemistryRuntime";
export {
  CHEM_MATERIALS,
  deriveChemConditions,
  getChemMaterial,
  isBurning,
} from "./chemistry";
export type {
  ChemAxes,
  ChemCondition,
  ChemMaterial,
  ChemReactionRecord,
  CellChemRecord,
} from "./chemistry";
export {
  IMMERSIVE_AMBIENT_TEMPERATURE,
  IMMERSIVE_ENERGY_PER_SPEED_PER_SEGMENT,
  IMMERSIVE_GLOBAL_VERBS,
  IMMERSIVE_REACTION_RULES,
  IMMERSIVE_SEGMENTS_PER_TURN,
  IMMERSIVE_STANDARD_ACTION_ENERGY,
  advanceImmersivePerceptionForSave,
  advanceImmersiveReactionsForSave,
  advanceImmersiveScheduler,
  advanceImmersiveStage2Save,
  advanceImmersiveStage2Snapshot,
  advanceImmersiveTileLayerSnapshot,
  advanceImmersiveWorldStateForSave,
  applyImmersiveCombatAttackToSave,
  applyImmersiveCombatForcedMovementToSave,
  applyImmersiveGlobalVerbToSave,
  applyImmersiveOverwatchToMovementSave,
  applyImmersivePlayerOverwatchToSave,
  createImmersiveCombatTacticalSnapshotFromV1,
  createImmersivePerceptionSnapshotFromV1,
  createImmersiveSpatialInventorySnapshotFromSave,
  createImmersiveTileLayerRecords,
  createImmersiveSchedulerStateFromV1,
  createImmersiveStage2SnapshotFromV1,
  createImmersiveTileLayerSnapshot,
  evaluateImmersiveWorldStateForSave,
  relaxTemperatureTowardAmbient,
  resolveImmersiveReactions,
  writeImmersiveTileLayerSnapshotToSave,
} from "./immersiveSim";
export type {
  ImmersiveGasLayerState,
  ImmersiveCombatActorSnapshot,
  ImmersiveCombatAttackOptions,
  ImmersiveCombatAttackResult,
  ImmersiveCombatCoverEdge,
  ImmersiveCombatCoverStrength,
  ImmersiveCombatForcedMovementOptions,
  ImmersiveCombatForcedMovementResult,
  ImmersiveCombatIntentRecord,
  ImmersiveCombatOverwatchTrigger,
  ImmersiveCombatOverwatchZone,
  ImmersiveCombatTeam,
  ImmersiveDetectionCause,
  ImmersiveGlobalVerbKind,
  ImmersiveGlobalVerbOptions,
  ImmersiveGlobalVerbResult,
  ImmersivePlayerOverwatchResult,
  ImmersiveLiquidLayerState,
  ImmersivePerceptionAlertRecord,
  ImmersivePerceptionStimulus,
  ImmersiveReactionRuleDefinition,
  ImmersiveReactionRecord,
  ImmersiveReactionResolveResult,
  ImmersiveReactionSaveResult,
  ImmersiveReactionStatusApplication,
  ImmersiveSchedulerAdvanceResult,
  ImmersiveSchedulerEvent,
  ImmersiveStage4PerceptionAdvanceResult,
  ImmersiveStage4PerceptionSnapshot,
  ImmersiveStage6TacticalSnapshot,
  ImmersiveSpatialInventoryItem,
  ImmersiveSpatialInventoryOptions,
  ImmersiveSpatialInventorySnapshot,
  ImmersiveAlertnessState,
  ImmersiveStage2SaveAdvanceResult,
  ImmersiveStage2Snapshot,
  ImmersiveTileLayerCellState,
  ImmersiveTileLayerSnapshot,
  ImmersiveWorldPassiveCheckDefinition,
  ImmersiveWorldStateAdvanceOptions,
  ImmersiveWorldStateAdvanceResult,
  ImmersiveWorldStateEvaluation,
  ImmersiveWorldStateEvaluationOptions,
  ImmersiveWorldStateGateResult,
} from "./immersiveSim";
